### ISSUE TITLE
Feature 1: User can view random anime recommendations

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the whole page set up and the recommended list of animes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The web page will request a get from a Jikan API and query the DOM to generate a recommend list. it will show an image of the Anime and the Title to the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/182212249-384f7aca-df22-4be3-bb55-700f61f66922.png)
![image](https://user-images.githubusercontent.com/106636383/182212302-9d20ee5b-c196-4736-8dbe-5ddc369fe5a5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can see the page set up the header
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] The header is responsive.
- [x] User can see the explain of what will generate <h#>
- [x] test the layout model to check if it looks accurate and works the way it's suppose to
- [x] XMLHttpRequest so that it can get information from the API.
- [x] will push the information to the data model
- [x] get the image and the title to show on the webpage and layout is same as the layout model.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
