### ISSUE TITLE
Feature 2: User can search an anime based on genre

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for anime based on genre

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user selects a genre, the recommend list will disappear and will be replace with new anime list based on the genre

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/182212408-8cc26dd0-f058-46ec-b85d-0cfa4486574c.png)
![image](https://user-images.githubusercontent.com/106636383/182212439-2f7d8bd6-8ac0-4f23-ba2f-9244515cc2f8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can use the Genre select option.
- [x] once clicked it will show the available options
- [x] Use the API to get the genre according to the selected option.
   - [x] each genre will have a unique number per API, will need to have something to match the select text to conver to correct genre ID number.
- [x] once an option is selected, the recommend view will be hidden and will show the anime list according to genre
   - [x] get the based on the data model, view of random to hide and open the unhide recommend
   - [x] will get the API to match the genre selected.
   - [x] the response will generate the image and the title according to the layout model
   - [x] the result should show at least 12
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
