### ISSUE TITLE
Feature 3: User can see the summary/info about the anime

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the summary/info about the anime

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Application will also grab additional data about the anime displayed to give more information about the shown anime. for both recommended list and the genre selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/106636383/182675483-ebd29c64-1b6a-4360-96e4-266c99e26170.png)
![image](https://user-images.githubusercontent.com/106636383/182675648-0da6690c-ae5e-496f-8877-d0edb2f9563e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Test the API to get the information
   - [x] once can get, check if it is the correct information
   - [x] use CSS to show accurately to the layout model.
   - [x] render DOM and the infomation should below the title.
- [x] feature should work with all anime list (recommend & genre)
- [x] if the information provided is longer than the height space available for the wrapper 
   - [x] use text-overflow property (possibly ellipsis value)
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
