### ISSUE TITLE
Feature 4: User can like (add as favorite) the anime

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like (add as favorite) the anime

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user see the anime that they want to add to their favorite list, can click on the "add to favorite" button

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/182720498-604aac65-ad01-4632-a805-8e568fdd6225.png)
![image](https://user-images.githubusercontent.com/106636383/182720548-7006badd-c2a8-4e12-be57-e8d2bdb5fb7c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create an <a> or <button> for "Add to Favorite"
   - [x] if <a> make it look like a button
   - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] "Add to Favorite" should sit below the image on mobile
   - [x] should be place next to image above the title on desktop
- [x] once clicked the color of "Add to Favorite" should change
   - [x] the text will chage to "Added to Favorite" and the background color should change
   - [x] the information should be save to the data model
   - [x] if the the page is loaded to different genre, but has the same anime (since holds many genre) the "Added to Favorite" should still remain.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
