### ISSUE TITLE
Feature 5: User can view the lists of liked (favorited) anime

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the lists of liked (favorited) anime

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the User clicks on the favorite nav link, can view all the lists that the user like (added to favorite)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/182975024-fa28df2d-b847-4c85-9320-7035d9d8563b.png)
![image](https://user-images.githubusercontent.com/106636383/182974986-6d46b998-82e8-4812-86d8-9831ed3f3e66.png)
![image](https://user-images.githubusercontent.com/106636383/182975064-d82c1611-d667-4027-9375-3fb77a2536bf.png)
![image](https://user-images.githubusercontent.com/106636383/182975087-8acfa0e0-e036-43cf-bf39-5fd432d6603e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an `<a>` for Favorite on top right on mobile,  in between Anime and Genre on Mobile
   - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse. 
   - [x] on click of Favorite, it will show a new view of "My Favorites" with a different font
   - [x] if there is no favorite list, should show that "There Are No Favorite Animes Added"
 - [x] if there is a favorite, the list should render from the data model.
    - [x] the list should be rendering in the same design and layout.
- [x] if view is not on Genre, the select option will default back to select
- [x] clicking the button while the anime was already added to favorite will remove the anime from favorite.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
